### ISSUE TITLE
Password security

### ISSUE THREAD

**Issue by bartmin** [sam0hack/php#3]
There is a risk that if someone got access to your application database, he would also know all passwords.

Solution: at least replace

``` php
mysql_query("update doctor_login set password='$newp' where username='$username'")or die(mysql_error());
```

to

``` php
$newp = sha1($newp);
mysql_query("update doctor_login set password='$newp' where username='$username'")or die(mysql_error());
```

and do so in all files where such SQL SET command is used.

Better solution would be to use _salt_. If you don't know what _salt_ is, there's a lot of info and tutorials on Google. Generally, the way it works is you don't save just a hash of user-submitted password, but you append to this a piece of randomly generated data (like _microtime()_), and just then hash it; additionally, you save this randomly generated data in your database. It makes a password harder to break in case of database break-in (see "Rainbow tables" in Google).

**Comment by sam0hack** [comment]
It's was a prototype and it's very old code. i was thinking convert this into laravel but i need some awesome programmer.

**Comment by bartmin** [comment]
Unfortunately, I don't know Laravel. But it looks as nice idea :) Have luck!

2015-09-19 20:09 GMT+02:00 sameer notifications@github.com:

> It's was a prototype and it's very old code. i was thinking convert this
> into laravel but i need some awesome programmer.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codex8/php/issues/3#issuecomment-141694432.

## 

Michał Bartmiński

**Comment by sam0hack** [comment]
thanks @bartmin :+1:
